# Generated by usvc-1.15.0
# Feel free to adjust, it will not be overridden

FROM renderedtext/elixir:1.6.5-v2

ENV TERM=xterm
ENV MIX_ENV=prod

COPY mix.exs ./
COPY config/ config/

USER root
RUN mix do local.hex --force, local.rebar --force, deps.get, compile; \
    chown dev.dev -R ../

COPY mix.* ./
RUN mix do deps.get, compile; \
    chown dev.dev -R ../

COPY lib lib/
COPY test test/

RUN chown dev.dev -R lib test

USER dev
RUN mix compile

CMD elixir --sname green_worker -S mix run --no-halt

