# Generated by usvc-1.15.0
# Feel free to adjust, it will not be overridden

.PHONY: image.build image.run image.test image.push image.pull
.PHONY: create-deploy deploy k8s-shell console watch lint
.PHONY: config-gen abort-on-uncommited-changes copy-mix.lock db.init

ELIXIR_DOCKER_IMAGE=renderedtext/elixir-dev:1.6.5-v2

APP_NAME=green_worker
APP_NAME_DASH=green-worker
APP_VSN=`grep 'version:' mix.exs | cut -d '"' -f2`

SEMAPHORE_EXECUTABLE_UUID?=""
GIT_HASH=$(shell git log --format=format:'%h' -1)
export TAG?=$(GIT_HASH)-$(SEMAPHORE_EXECUTABLE_UUID)
export REPO=renderedtext/$(APP_NAME)
IMAGE=$(REPO):$(TAG)
IMAGE_LATEST=$(REPO):latest
DEPLOY_FILE=deploy.yml
DEPLOY_FILE_TEMPLATE=$(DEPLOY_FILE).template
export IMAGE_PULL_SECRETS=imagePullSecrets: [name: dockerhub-secrets]
APP_NAME=`grep 'app:' mix.exs | cut -d ':' -f3 | cut -d ',' -f1`
APP_VSN=`grep 'version:' mix.exs | cut -d '"' -f2`

HOME_DIR=/home/dev
REPO_DIR=$(HOME_DIR)/repo
WORKDIR=$(REPO_DIR)/$(APP_NAME)
USER=dev

CONTAINER_ENV_VARS= \
	-e APP_ENV=$(APP_ENV) \

INTERACTIVE_SESSION=\
  -v $$PWD/home_dir:$(HOME_DIR) \
  -v $$PWD/..:$(REPO_DIR) \
  --rm \
  --workdir=$(WORKDIR) \
  --user=$(USER) \
  -it $(ELIXIR_DOCKER_IMAGE)

CMD?=/bin/bash

console: make_fs_home_dir
	docker run --network=host $(CONTAINER_ENV_VARS) $(INTERACTIVE_SESSION) $(CMD)

image.build:
	docker build --cache-from $(IMAGE_LATEST) -t $(IMAGE) .
	docker tag $(IMAGE) $(IMAGE_LATEST)

image.run: image.build
	docker run -p 4000:4000 -it $(IMAGE)

# Container litens on different port
# (so that container and 'mix run' can run together)
image.test: image.build
	docker run --rm --name $(APP_NAME) -p 4004:4000 -d $(IMAGE)
	# run some tests...
	docker kill $(APP_NAME)

RELEASE_DIR=rel/artifacts
release:
	$(MAKE) console MIX_ENV=prod CMD="mix release --verbose"
	mkdir -p $(RELEASE_DIR)
	cp "_build/prod/rel/$(APP_NAME)/releases/$(APP_VSN)/$(APP_NAME).tar.gz" $(RELEASE_DIR)/"$(APP_NAME)-$(APP_VSN).tar.gz"

deploy: abort-on-uncommited-changes image.push config-gen
	kubectl apply -f deploy.yml
	kubectl get svc/$(APP_NAME_DASH)

k8s-shell:
	$(eval pod_name=$(shell kubectl get po -l app=cluster-portal -o jsonpath={.items[*].metadata.name}))
	kubectl exec -it $(pod_name) -- /bin/bash

watch:
	docker run --network=host $(CONTAINER_ENV_VARS) $(INTERACTIVE_SESSION) \
         mix do deps.get, test.watch

lint:
	$(MAKE) console CMD="mix do credo"

lint-root:
	$(MAKE) console USER=root CMD="mix do local.hex --force, local.rebar --force, deps.get, credo"

postgres.run:
	docker run -d --rm --name db --network=host postgres:9.6
	@echo "\nWaiting for DB to become operational"
	sleep 5
	$(MAKE) db.init

db.init:
	$(MAKE) console MIX_ENV=$(MIX_ENV) USER=$(USER) CMD="mix do ecto.create, ecto.migrate"
	@echo "\nDatabase '$(DB_NAME)' created and migrated."
	@echo "\nConnect with: 'psql -h localhost -U postgres $(DB_NAME)'"

image.push: image.build
	docker push $(IMAGE)
	docker push $(IMAGE_LATEST)

image.pull:
	docker pull $(IMAGE)
	docker pull $(IMAGE_LATEST)

config-gen:
	envsubst '$${REPO} $${TAG} $${IMAGE_PULL_SECRETS}' < $(DEPLOY_FILE_TEMPLATE) > $(DEPLOY_FILE)
	cat $(DEPLOY_FILE)

abort-on-uncommited-changes:
	git diff-index --quiet HEAD --

make_fs_home_dir:
	mkdir -p home_dir
