# Generated by usvc-1.15.0
# Feel free to adjust, it will not be overridden

defmodule GreenWorker.Mixfile do
  use Mix.Project

  def project do
    [app: :green_worker,
     version: "0.2.0",
     elixir: "~> 1.6",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [extra_applications: [:logger],
     mod: {GreenWorker.Application, []}]
  end

  defp deps do
    [
      {:distillery, "~> 2.0"},
      {:postgrex, "~> 0.14"},
      {:ecto, "~> 3.0"},
      {:ecto_sql, "~> 3.0"},
      {:credo, "~> 0.8", only: [:dev, :test], runtime: false},
      {:uuid, "~> 1.1"},
    ]
  end
end
